import type { ProjectContentFactory } from "@/lib/types";

const content: ProjectContentFactory = (locale) => {
  if (locale === "pt") {
    return {
      context: (
        <>
          <p>
            HackerNewsPlus é um cliente web para o Hacker News que consome duas
            APIs públicas. O usuário navega pelos posts do front page, posts mais
            recentes, busca por título, visualiza comentários de uma story e
            acessa o perfil de qualquer autor. Interface full dark mode
            construída com Bootstrap 5.
          </p>
        </>
      ),
      decisions: [
        {
          title: "DOMPurify para sanitização de HTML externo",
          body: (
            <>
              <p>
                A HN API retorna comentários e o campo &ldquo;about&rdquo; dos
                usuários como HTML bruto gerado por terceiros. Antes de
                qualquer <code>dangerouslySetInnerHTML</code>, o conteúdo passa
                por <code>DOMPurify.sanitize()</code>. Sem isso, qualquer
                usuário do HN poderia injetar scripts que rodariam no contexto
                do cliente.
              </p>
            </>
          ),
        },
        {
          title: "Duas APIs distintas para domínios distintos",
          body: (
            <>
              <p>
                Posts, comentários e busca usam a Algolia HN Search API — que
                tem suporte nativo a paginação, full-text search e filtros por
                tag. Perfis de usuário usam a Firebase HN API oficial, única
                fonte que expõe karma e about. Separar as chamadas por
                responsabilidade evita workarounds para buscar dados que uma
                API não tem.
              </p>
            </>
          ),
        },
      ],
    };
  }

  return {
    context: (
      <>
        <p>
          HackerNewsPlus is a web client for Hacker News consuming two public
          APIs. Users browse the front page, recent posts, search by title,
          view story comments and access any author&rsquo;s profile. Full dark
          mode interface built with Bootstrap 5.
        </p>
      </>
    ),
    decisions: [
      {
        title: "DOMPurify for external HTML sanitization",
        body: (
          <>
            <p>
              The HN API returns comments and user &ldquo;about&rdquo; fields
              as raw HTML generated by third parties. Before any{" "}
              <code>dangerouslySetInnerHTML</code>, content goes through{" "}
              <code>DOMPurify.sanitize()</code>. Without this, any HN user
              could inject scripts running in the client&rsquo;s context.
            </p>
          </>
        ),
      },
      {
        title: "Two distinct APIs for distinct domains",
        body: (
          <>
            <p>
              Posts, comments and search use the Algolia HN Search API — with
              native pagination, full-text search and tag filters. User
              profiles use the official Firebase HN API, the only source
              exposing karma and about. Splitting calls by responsibility
              avoids workarounds for data one API doesn&rsquo;t have.
            </p>
          </>
        ),
      },
    ],
  };
};

export default content;
